### ISSUE TITLE
mox test documentation issue

### ISSUE THREAD

**Issue by stocks29** [breakroom/snap#102]
when following [the test instructions](https://hexdocs.pm/snap/readme.html#testing) the application fails to start during `mix test` because the `child_spec` stub is not defined yet because `test_helper.exs` runs after the application starts and therefore the cluster attempts to start.

```
** (Mix) Could not start application my_app: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: MyApp.Cluster
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function MyApp.HTTPClientMock.child_spec/1 is undefined (module MyApp.HTTPClientMock is not available)
            MyApp.HTTPClientMock.child_spec([cluster: MyApp.Cluster, url: "https://localhost:9999", username: "doesnotexist", password: "notarealpassword", http_client_adapter: MyApp.HTTPClientMock])
            (snap 0.10.0) lib/snap/supervisor.ex:45: Snap.Cluster.Supervisor.maybe_initialize_http_client/2
            (snap 0.10.0) lib/snap/supervisor.ex:29: Snap.Cluster.Supervisor.init/1
            (stdlib 5.1) supervisor.erl:330: :supervisor.init/1
            (stdlib 5.1) gen_server.erl:962: :gen_server.init_it/2
            (stdlib 5.1) gen_server.erl:917: :gen_server.init_it/6
            (stdlib 5.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

I've tried using Mox's [compile-time requirements](https://hexdocs.pm/mox/1.0.0/Mox.html#module-compile-time-requirements) but it's not possible to define stubs at compile time.

Am I missing something in this approach?

**Comment by stocks29** [comment]
I was able to get this working by defining a proxy module which defines `child_spec` and then delegates `request()` calls to the mock module.

```
# test/support/http_client_mock_proxy.ex
defmodule MyApp.HTTPClientMockProxy do
  @behaviour Snap.HTTPClient

  @impl Snap.HTTPClient
  def child_spec(_config), do: :skip

  @impl Snap.HTTPClient
  def request(cluster, method, url, headers, body, opts) do
    impl().request(cluster, method, url, headers, body, opts)
  end

  defp impl() do
    Application.get_env(:my_app, __MODULE__)[:http_client_adapter]
  end
end

# config/test.exs
config :hydra, MyApp.Search.Cluster, http_client_adapter: MyApp.HTTPClientMockProxy
config :hydra, MyApp.HTTPClientMockProxy, http_client_adapter: MyApp.HTTPClientMock

# test_helper.exs
Mox.defmock(MyApp.HTTPClientMock, for: Snap.HTTPClient)
```

maybe include something like this in the docs?

**Comment by feynmanliang** [comment]
+1, I have to override the module definition

```elixir
defmodule DreamcatcherWeb.HTTPClientMock do
  def child_spec(_), do: :skip
end
config :dreamcatcher, Dreamcatcher.Elasticsearch,
  http_client_adapter: DreamcatcherWeb.HTTPClientMock
```
