### ISSUE TITLE
Problems with tests

### ISSUE THREAD

**Issue by joaopsramos** [breakroom/snap#15]
Hello!

I am not able to test as it is in the documentation, following the test guide, the application does not start:
```elixir
** (MatchError) no match of right hand side value: {:error, {:ioms, {{:shutdown, {:failed_to_start_child, Ioms.Cluster, {:undef, [{HTTPClientMock, :child_spec, [[cluster: Ioms.Cluster, url: "http://localhost:9200", username: "username", password: "password", http_client_adap
ter: HTTPClientMock]], []}, {Snap.Cluster.Supervisor, :maybe_initialize_http_client, 2, [file: 'lib/snap/supervisor.ex', line: 36]}, {Snap.Cluster.Supervisor, :init, 1, [file: 'lib/snap/supervisor.ex', line: 24]}, {:supervisor, :init, 1, [file: 'supervisor.erl', line: 330]},
 {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 423]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 390]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}}, {Ioms.Application, :start, [:normal, []]}}}}
```

I have to remove the Cluster from the application, use `setup :set_mox_global` with `async: false` (not desired) and on test setup:
```elixir
setup do
  Mox.stub(HTTPClientMock, :child_spec, fn _config -> :skip end)
  Ioms.Cluster.start_link([])
end
```

Is there a better way to test?

**Comment by feynmanliang** [comment]
I ran into a similar issue following the [readme instructions for testing](https://github.com/breakroom/snap#testing); it seems like the `Mox.stub/2` of `HTTPClientMock.child_spec/1` inside `test_helpers.exs` is not being applied before the supervision tree is started up

```
** (Mix) Could not start application farmyard: FarmyardWeb.Application.start(:normal, []) returned an error: shutdown: failed to start child: Farmyard.Elasticsearch
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function HTTPClientMock.child_spec/1 is undefined (module HTTPClientMock is not available)
            HTTPClientMock.child_spec([cluster: Farmyard.Elasticsearch, url: "http://localhost:9200", username: "elastic", password: "changeme", http_client_adapter: HTTPClientMock])
            (snap 0.8.1) lib/snap/supervisor.ex:36: Snap.Cluster.Supervisor.maybe_initialize_http_client/2
            (snap 0.8.1) lib/snap/supervisor.ex:24: Snap.Cluster.Supervisor.init/1
            (stdlib 4.3) supervisor.erl:330: :supervisor.init/1
            (stdlib 4.3) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.3) gen_server.erl:814: :gen_server.init_it/6
            (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

In my case, I ended up mocking `MyApp.Cluster` instead.

**Comment by feynmanliang** [comment]
Can not recommend ^^; beside the warning I am seeing failures in Github actions not reproducible locally.

**Comment by nmingazov** [comment]
Hey :) It looks like solution to this one was reverted, shall we re-open the issue as well?
