### ISSUE TITLE
:auth is required?

### ISSUE THREAD

**Issue by nics** [breakroom/snap#2]
Hi,

the docs say that :auth is optional in the config, but when omitted I get an error:

```
** (KeyError) key :auth not found in: [url: "http://localhost:9200"]
    (elixir 1.11.3) lib/keyword.ex:420: Keyword.fetch!/2
    (snap 0.4.1) lib/snap/request.ex:7: Snap.Request.request/7
    (snap 0.4.1) lib/snap/indexes/indexes.ex:85: Snap.Indexes.list/2
```

Kind regards,
Nicolas

**Comment by tomtaylor** [comment]
Thanks, fixed in d9a4a32fdedd285186cd1ad2af88c23c7547cf62!
